"""initial

Revision ID: 2720dadfc4f1
Revises: 
Create Date: 2026-04-22 08:04:12.587913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2720dadfc4f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pair', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pair', 'date')
    )
    op.create_index(op.f('ix_fx_daily_pair'), 'fx_daily', ['pair'], unique=False)
    op.create_table('tickers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('last_price_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickers_symbol'), 'tickers', ['symbol'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticker_prices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('adj_close', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'date')
    )
    op.create_index(op.f('ix_ticker_prices_date'), 'ticker_prices', ['date'], unique=False)
    op.create_index(op.f('ix_ticker_prices_ticker_id'), 'ticker_prices', ['ticker_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('async_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('result_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_async_jobs_workspace_id'), 'async_jobs', ['workspace_id'], unique=False)
    op.create_table('backtest_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('base_currency', sa.String(length=10), nullable=False),
    sa.Column('commission_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('slippage_bps', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('rebalance_mode', sa.String(length=20), nullable=False),
    sa.Column('deduplicate', sa.Boolean(), nullable=False),
    sa.Column('exclude_llm_errors', sa.Boolean(), nullable=False),
    sa.Column('use_equal_weight_bench', sa.Boolean(), nullable=False),
    sa.Column('use_random_bench', sa.Boolean(), nullable=False),
    sa.Column('random_simulations', sa.Integer(), nullable=False),
    sa.Column('external_index_symbol', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_runs_workspace_id'), 'backtest_runs', ['workspace_id'], unique=False)
    op.create_table('upload_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('week_date', sa.Date(), nullable=False),
    sa.Column('xlsx_s3_key', sa.String(length=500), nullable=True),
    sa.Column('txt_s3_key', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'week_date')
    )
    op.create_index(op.f('ix_upload_batches_workspace_id'), 'upload_batches', ['workspace_id'], unique=False)
    op.create_table('workspace_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id')
    )
    op.create_index(op.f('ix_workspace_memberships_user_id'), 'workspace_memberships', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_memberships_workspace_id'), 'workspace_memberships', ['workspace_id'], unique=False)
    op.create_table('backtest_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('total_return', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cagr', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('volatility', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sortino_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('calmar_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('turnover', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pct_random_beaten', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('equity_curve', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_metrics_run_id'), 'backtest_metrics', ['run_id'], unique=False)
    op.create_table('backtest_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cash', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_snapshots_run_id'), 'backtest_snapshots', ['run_id'], unique=False)
    op.create_table('weekly_selections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('week_date', sa.Date(), nullable=False),
    sa.Column('model_phase1', sa.String(length=50), nullable=True),
    sa.Column('model_phases234', sa.String(length=50), nullable=True),
    sa.Column('total_analyzed', sa.Integer(), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('alerts', sa.Text(), nullable=True),
    sa.Column('diversification', sa.Text(), nullable=True),
    sa.Column('final_considerations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['upload_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'week_date')
    )
    op.create_index(op.f('ix_weekly_selections_workspace_id'), 'weekly_selections', ['workspace_id'], unique=False)
    op.create_table('weekly_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('ticker_id', sa.UUID(), nullable=False),
    sa.Column('week_date', sa.Date(), nullable=False),
    sa.Column('cagr_pot', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('mediana_retorno_l5y', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pct_3m_alcista_5y', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('mod1y_ev_ebit', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('mod1y_ev_ebitda', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('mod1y_p_fcf', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('mod1y_per', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('growth_rev_est_pend', sa.String(length=50), nullable=True),
    sa.Column('anal_rev_growth', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('gross_margin_pend', sa.String(length=50), nullable=True),
    sa.Column('net_income_pend', sa.String(length=50), nullable=True),
    sa.Column('annual_pct_buyback_3y', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('dividend_yield_3y', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('net_debt_ebitda_1y', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pq_barata', sa.Text(), nullable=True),
    sa.Column('orden', sa.Text(), nullable=True),
    sa.Column('estado_perf_vs_ev', sa.String(length=200), nullable=True),
    sa.Column('perfil_compounder', sa.String(length=50), nullable=True),
    sa.Column('ai_directiva', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('valores_crecimiento', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('antiguedad_directiva', sa.Text(), nullable=True),
    sa.Column('caida_acciones', sa.Text(), nullable=True),
    sa.Column('calidad_directiva', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cortos_motivo', sa.Text(), nullable=True),
    sa.Column('evo_market_share', sa.Text(), nullable=True),
    sa.Column('fijacion_precios', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('guidance_search', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('potencial_fraude', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_news_list', sa.Text(), nullable=True),
    sa.Column('risk_transcript_list', sa.Text(), nullable=True),
    sa.Column('sensibilidad_macro', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('subida_acciones', sa.Text(), nullable=True),
    sa.Column('customer_concentration_risk', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['upload_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'ticker_id', 'week_date')
    )
    op.create_index(op.f('ix_weekly_signals_ticker_id'), 'weekly_signals', ['ticker_id'], unique=False)
    op.create_index(op.f('ix_weekly_signals_week_date'), 'weekly_signals', ['week_date'], unique=False)
    op.create_index(op.f('ix_weekly_signals_workspace_id'), 'weekly_signals', ['workspace_id'], unique=False)
    op.create_table('backtest_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.UUID(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('weight', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['backtest_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_positions_snapshot_id'), 'backtest_positions', ['snapshot_id'], unique=False)
    op.create_table('company_dossiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('selection_id', sa.UUID(), nullable=False),
    sa.Column('ticker_id', sa.UUID(), nullable=False),
    sa.Column('dossier_order', sa.Integer(), nullable=False),
    sa.Column('growth_profile', sa.Text(), nullable=True),
    sa.Column('margins_efficiency', sa.Text(), nullable=True),
    sa.Column('financial_health', sa.Text(), nullable=True),
    sa.Column('relative_valuation', sa.Text(), nullable=True),
    sa.Column('management_quality', sa.Text(), nullable=True),
    sa.Column('main_risks', sa.Text(), nullable=True),
    sa.Column('key_opportunities', sa.Text(), nullable=True),
    sa.Column('general_conclusion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['selection_id'], ['weekly_selections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('selection_picks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('selection_id', sa.UUID(), nullable=False),
    sa.Column('ticker_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('role_activity', sa.String(length=255), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['selection_id'], ['weekly_selections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('selection_picks')
    op.drop_table('company_dossiers')
    op.drop_index(op.f('ix_backtest_positions_snapshot_id'), table_name='backtest_positions')
    op.drop_table('backtest_positions')
    op.drop_index(op.f('ix_weekly_signals_workspace_id'), table_name='weekly_signals')
    op.drop_index(op.f('ix_weekly_signals_week_date'), table_name='weekly_signals')
    op.drop_index(op.f('ix_weekly_signals_ticker_id'), table_name='weekly_signals')
    op.drop_table('weekly_signals')
    op.drop_index(op.f('ix_weekly_selections_workspace_id'), table_name='weekly_selections')
    op.drop_table('weekly_selections')
    op.drop_index(op.f('ix_backtest_snapshots_run_id'), table_name='backtest_snapshots')
    op.drop_table('backtest_snapshots')
    op.drop_index(op.f('ix_backtest_metrics_run_id'), table_name='backtest_metrics')
    op.drop_table('backtest_metrics')
    op.drop_index(op.f('ix_workspace_memberships_workspace_id'), table_name='workspace_memberships')
    op.drop_index(op.f('ix_workspace_memberships_user_id'), table_name='workspace_memberships')
    op.drop_table('workspace_memberships')
    op.drop_index(op.f('ix_upload_batches_workspace_id'), table_name='upload_batches')
    op.drop_table('upload_batches')
    op.drop_index(op.f('ix_backtest_runs_workspace_id'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_index(op.f('ix_async_jobs_workspace_id'), table_name='async_jobs')
    op.drop_table('async_jobs')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_ticker_prices_ticker_id'), table_name='ticker_prices')
    op.drop_index(op.f('ix_ticker_prices_date'), table_name='ticker_prices')
    op.drop_table('ticker_prices')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tickers_symbol'), table_name='tickers')
    op.drop_table('tickers')
    op.drop_index(op.f('ix_fx_daily_pair'), table_name='fx_daily')
    op.drop_table('fx_daily')
    # ### end Alembic commands ###
