"""f2_5_initial_schema_8_tables

Revision ID: e332ea7d1de0
Revises: 
Create Date: 2026-06-03 12:52:45.889994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e332ea7d1de0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('google_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('viewer', 'analyst', 'admin')", name='ck_app_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('fx_daily',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('pair', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('source', sa.String(), server_default='yfinance', nullable=False),
    sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pair', 'date', name='uq_fx_daily_pair_date')
    )
    op.create_table('price_cache_daily',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('adj_close', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('source', sa.String(), server_default='yfinance', nullable=False),
    sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'price_date', name='uq_price_cache_ticker_date')
    )
    op.create_table('backtest',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('period', postgresql.DATERANGE(), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('base_currency', sa.String(), server_default='USD', nullable=False),
    sa.Column('strategy_code', sa.String(), nullable=False),
    sa.Column('benchmark_code', sa.String(), nullable=False),
    sa.Column('weeks_total', sa.Integer(), nullable=True),
    sa.Column('weeks_processed', sa.Integer(), nullable=True),
    sa.Column('error_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed', 'cancelled')", name='ck_backtest_status'),
    sa.CheckConstraint('NOT isempty(period)', name='ck_backtest_period_not_empty'),
    sa.CheckConstraint('initial_capital > 0', name='ck_backtest_initial_capital_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backtest_created_at_desc', 'backtest', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index('ix_backtest_created_by', 'backtest', ['created_by'], unique=False)
    op.create_index('ix_backtest_status', 'backtest', ['status'], unique=False)
    op.create_table('backtest_equity_point',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('backtest_id', sa.UUID(), nullable=False),
    sa.Column('series', sa.String(), nullable=False),
    sa.Column('point_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.CheckConstraint("series IN ('portfolio', 'benchmark')", name='ck_equity_point_series'),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtest.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('backtest_id', 'series', 'point_date', name='uq_equity_point_backtest_series_date')
    )
    op.create_table('backtest_result',
    sa.Column('backtest_id', sa.UUID(), nullable=False),
    sa.Column('total_return', sa.Numeric(), nullable=True),
    sa.Column('cagr', sa.Numeric(), nullable=True),
    sa.Column('volatility', sa.Numeric(), nullable=True),
    sa.Column('sharpe', sa.Numeric(), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(), nullable=True),
    sa.Column('metrics_extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtest.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('backtest_id')
    )
    op.create_table('backtest_snapshot_week',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('backtest_id', sa.UUID(), nullable=False),
    sa.Column('week_date', sa.Date(), nullable=False),
    sa.Column('resolved_run_id', sa.Integer(), nullable=False),
    sa.Column('run_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtest.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('backtest_id', 'week_date', name='uq_snapshot_week_backtest_date')
    )
    op.create_index('ix_snapshot_week_backtest_id', 'backtest_snapshot_week', ['backtest_id'], unique=False)
    op.create_table('backtest_snapshot_pick',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_week_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('fx_pair', sa.String(), nullable=True),
    sa.Column('fx_rate', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_week_id'], ['backtest_snapshot_week.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_week_id', 'ticker', name='uq_snapshot_pick_week_ticker')
    )
    op.create_index('ix_snapshot_pick_snapshot_week_id', 'backtest_snapshot_pick', ['snapshot_week_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_snapshot_pick_snapshot_week_id', table_name='backtest_snapshot_pick')
    op.drop_table('backtest_snapshot_pick')
    op.drop_index('ix_snapshot_week_backtest_id', table_name='backtest_snapshot_week')
    op.drop_table('backtest_snapshot_week')
    op.drop_table('backtest_result')
    op.drop_table('backtest_equity_point')
    op.drop_index('ix_backtest_status', table_name='backtest')
    op.drop_index('ix_backtest_created_by', table_name='backtest')
    op.drop_index('ix_backtest_created_at_desc', table_name='backtest', postgresql_ops={'created_at': 'DESC'})
    op.drop_table('backtest')
    op.drop_table('price_cache_daily')
    op.drop_table('fx_daily')
    op.drop_table('app_user')
    # ### end Alembic commands ###
